# Generated by Django 5.2 on 2025-05-28 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_task_id_event_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSyncMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sync_metadata', to='events.event')),
            ],
            options={
                'unique_together': {('event', 'provider')},
            },
        ),
    ]
