# Generated by Django 5.2 on 2025-05-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventsyncmetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsyncmetadata',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
