# Generated by Django 5.2 on 2025-05-31 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_event_alter_notification_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='scheduled_for',
        ),
        migrations.AddField(
            model_name='notification',
            name='remaining_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
