# Generated by Django 5.2 on 2025-05-17 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='external_id',
        ),
    ]
