# Generated by Django 5.2 on 2025-05-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='linked_to',
            field=models.CharField(choices=[('google', 'Google Calendar'), ('outlook', 'Outlook Calendar')], default='google', max_length=10),
        ),
    ]
