# Generated by Django 5.2 on 2025-05-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_linked_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='linked_to',
            field=models.CharField(choices=[('none', 'None'), ('google', 'Google Calendar'), ('outlook', 'Outlook Calendar')], default='none', max_length=10),
        ),
    ]
