# Generated by Django 5.2 on 2025-05-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_linked_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
