# Generated by Django 5.2 on 2025-05-28 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSyncMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=255)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_sync_metadata', to='tasks.task')),
            ],
            options={
                'unique_together': {('task', 'provider')},
            },
        ),
    ]
