# Generated by Django 5.2 on 2025-05-06 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiAssistant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_data', models.JSONField()),
                ('ai_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assistants', to='customusers.customuser')),
            ],
            options={
                'db_table': 'ai_assistant',
            },
        ),
    ]
