# Generated by Django 5.2 on 2025-05-06 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSync',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calendar_name', models.CharField(max_length=255)),
                ('sync_token', models.CharField(blank=True, max_length=255, null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_syncs', to='customusers.customuser')),
            ],
            options={
                'db_table': 'calendar_sync',
            },
        ),
    ]
