# Generated by Django 5.2 on 2025-05-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarsync', '0004_calendarevent_calendartask'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='calendarevent',
            name='calendar_ev_user_id_26e211_idx',
        ),
        migrations.RemoveIndex(
            model_name='calendarevent',
            name='calendar_ev_externa_5d57d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='calendartask',
            name='calendar_ta_user_id_f66a7e_idx',
        ),
        migrations.RemoveIndex(
            model_name='calendartask',
            name='calendar_ta_externa_26f409_idx',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='last_synced',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='recurrence_rule',
        ),
        migrations.RemoveField(
            model_name='calendartask',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='calendartask',
            name='last_synced',
        ),
        migrations.RemoveField(
            model_name='calendartask',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='calendartask',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='calendartask',
            name='recurrence_rule',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='external_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='calendartask',
            name='external_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
