# Generated by Django 5.2 on 2025-05-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarsync', '0005_remove_calendarevent_calendar_ev_user_id_26e211_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarsync',
            name='sync_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarsync',
            name='sync_status',
            field=models.CharField(choices=[('not_synced', 'Not Synced'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('error', 'Error')], default='not_synced', max_length=20),
        ),
    ]
