# Generated by Django 5.2 on 2025-05-16 09:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarsync', '0006_calendarsync_sync_error_calendarsync_sync_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendarevent',
            unique_together={('user', 'external_id', 'external_provider')},
        ),
    ]
