# Generated by Django 5.2 on 2025-05-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarsync', '0007_alter_calendarevent_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='last_synced_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
